name: psych_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '3.9.2'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  easy_stepper: ^0.9.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_local_notifications: ^19.5.0
  flutter_quill: ^11.5.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.2
  font_awesome_flutter: ^10.12.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  googleapis_auth: ^2.0.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  lottie: ^3.3.2
  path_provider: ^2.1.5
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  uuid: ^4.5.2
  webview_flutter: ^4.13.0
  
dev_dependencies:
  # build_runner: ^2.4.15
  build_runner: ^2.10.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.11.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/lottie/
    - .env
